export const MOVIES_ACTIONS = {
  GET_INITIAL_MOVIES_START: "GET_INITIAL_MOVIES_START",
  GET_INITIAL_MOVIES: "GET_INITIAL_MOVIES",
  GET_INITIAL_MOVIES_SUCCESS: "GET_INITIAL_MOVIES_SUCCESS",
  GET_INITIAL_MOVIES_FAIL: "GET_INITIAL_MOVIES_FAIL",
} as const;
