export const FILTERS_ACTIONS = {
  RESET_FILTERS: "RESET_FILTERS",
  GET_FILTERS_START: "GET_FILTERS_START",
  GET_FILTERS_ERROR: "GET_FILTERS_ERROR",
  GET_FILTERS_SUCCESS: "GET_FILTERS_SUCCESS",
  GET_FILTERS: "GET_FILTERS",
};
